name: Rejecting Pull Requests to Main from branches other than develop.

on:
  pull_request:
    branches:
      - '**'

jobs:
  reject_pr_job:
    runs-on: ubuntu-latest
    steps:      
      - name: Check branch name
        if: github.event.pull_request.base.ref == 'main'
        run: |
          if [ "$GITHUB_HEAD_REF" != "develop" && "$GITHUB_HEAD_REF" == "main" ]; then
            echo "Pull request not allowed from branch $GITHUB_HEAD_REF. Only pull requests from the develop branch are allowed."
            exit 1
          fi


